# Generated by Django 3.2.3 on 2021-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210625_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tema',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
