# Generated by Django 3.2.3 on 2021-06-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210627_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={},
        ),
    ]
