# Generated by Django 3.2.3 on 2021-06-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20210627_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='order',
            new_name='ordering',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='order',
            new_name='ordering',
        ),
        migrations.RenameField(
            model_name='tema',
            old_name='order',
            new_name='ordering',
        ),
    ]
