# Generated by Django 3.2.3 on 2021-06-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210627_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='ordering',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
