# Generated by Django 3.2.3 on 2021-06-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20210628_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='slug',
            field=models.SlugField(blank=True, default='name', null=True),
        ),
    ]
