# Generated by Django 3.2.3 on 2021-07-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='items.tema'),
        ),
    ]
